checks:
    php: true
build:
    environment:
        php:
            version: 7.2
    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: './clover.xml'
                    format: 'php-clover'
