language: php
php:
  - '7.2'
before_script: composer install
script: ./vendor/bin/phpunit
build:
    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
